### ISSUE TITLE
后台显示有问题

### ISSUE THREAD

**Issue by 1049759078** [pylixm/django-mdeditor#1]
配置好之后，在admin后台看，mdeditor编辑框一直转圈圈，不显示出来，审核元素查看之后发现很多个js和css没有找到

**Comment by sangyunxin** [comment]
我摸索了一下，发现解决方法时去下载editor.md的源文件：<https://github.com/pandao/editor.md>
然后把lib文件夹下的所有内容加入到项目文件的/static/js/lib/中。但这样好像仍然存在问题，主要是预览好像不是实时的，等待作者解答中。

**Comment by pylixm** [comment]
@sangyunxin editor.md 的加载是异步的所以可能会有停顿感。

@1049759078  可否将你的配置和代码贴下，我试了下，后台显示没问题，可能是我遗漏了什么地方。

**Comment by pylixm** [comment]
因长时间未反馈，默认已经解决。若还有问题可重新开启此issue的讨论，谢谢。

**Comment by PPJLiuJie** [comment]
这张图是显示效果，一直在加载进度条
![image](https://user-images.githubusercontent.com/6836711/51660348-693d2780-1fe8-11e9-9e5a-8d720190f22f.png)
这是通过chrome的Network捕获到的
![image](https://user-images.githubusercontent.com/6836711/51660363-76f2ad00-1fe8-11e9-8aee-ee9a0ca5fa8d.png)
下面是我工程的配置
![image](https://user-images.githubusercontent.com/6836711/51660458-ccc75500-1fe8-11e9-96d9-0760e5ccb4cf.png)
![image](https://user-images.githubusercontent.com/6836711/51660463-d5b82680-1fe8-11e9-97c6-96b001d8937c.png)
![image](https://user-images.githubusercontent.com/6836711/51660474-e10b5200-1fe8-11e9-86db-881fd7b06405.png)
![image](https://user-images.githubusercontent.com/6836711/51660499-f2545e80-1fe8-11e9-9537-cfb0d9e734e3.png)

其他环境：
python3.5.3
django1.8.2
django-mdeditor 0.1.10
...

**Comment by pylixm** [comment]
我检查了下这几个静态文件路径配置，应该不会出现你这种情况。可否把你这个几个文件现在的全路径发我看看。
![image](https://user-images.githubusercontent.com/15826317/51724709-8847c200-2099-11e9-9144-2369dc3c6e3f.png)

**Comment by PPJLiuJie** [comment]
我这边的路径是这样的 "/mdeditor/js/..."，缺少"/static"
为了解决这个问题，我拦截了以"mdeditor"开头的url，做了如下处理：

![image](https://user-images.githubusercontent.com/6836711/51725584-0dcd7100-209e-11e9-916b-3e5eb2cace7d.png)

![image](https://user-images.githubusercontent.com/6836711/51725599-1faf1400-209e-11e9-9dc0-656b24a416ea.png)



处理之后，就可以了。
我这边用的是 django1.8.2

**Comment by pylixm** [comment]
测试了下你这个问题，是django 1.8.x 和django2.x 对 ` {%staic '/mdeditor/js/lib'  %}  ` 解析不一致导致的，你使用django 2.x 或者使用我发布的最新版 v0.1.13 即可解决。
