### ISSUE TITLE
图片格式解析不正确

### ISSUE THREAD

**Issue by FormatToday** [pylixm/django-mdeditor#10]
在图片上传的时候，只允许设置的白名单，但是大写的就不行。比如设置了jpg，但是上传JPG时也会显示格式不对，所以希望全部进行upper或者lower处理，这样就可以了。
Python和js代码都需要修改，我自己尝试修改了Python代码，但是还是有格式不正确的提示。可是苦于不会js啊。。。

**Comment by pylixm** [comment]
已修正，可测试下。代码修改，见commit：https://github.com/pylixm/django-mdeditor/commit/0fbfdffc68c8bf3941f0803919516927a30310c2

**Comment by FormatToday** [comment]
谢啦。不过怎么是硬编码的。。。对文件后缀的字符串全部转为小写再去判断不是更好吗？在设置里也省的写大小写两种后缀了

**Comment by pylixm** [comment]
这里限制有2层，django这边的限制已经放开，支持大小写。还有一层限制是editormd中的`imageFormats`参数。它内部图片格式的默认值写死了，https://github.com/pandao/editor.md/blob/master/editormd.js#L149

**Comment by FormatToday** [comment]
哦哦，这样啊，那好吧。万分感谢
