### ISSUE TITLE
I can't see my result on WEB-Page!

### ISSUE THREAD

**Issue by icoder-new** [pylixm/django-mdeditor#110]
# Help wanted!
## I need help

Why i can't see result on my web page!
![Ashampoo_Snap_2020 07 17_17h39m44s_001_](https://user-images.githubusercontent.com/59335419/87787521-35496800-c855-11ea-8fc2-f065e821f08b.png)
![Ashampoo_Snap_2020 07 17_17h41m56s_002_](https://user-images.githubusercontent.com/59335419/87787557-45f9de00-c855-11ea-8a30-8c3f3dd26ed7.png)

:cry:

**Comment by icoder-new** [comment]
@pylixm Help Please!

**Comment by pylixm** [comment]
The text in the database is saved in markdown format, and the front-end display needs to be rendered by yourself.Here are some examples for reference.

- https://github.com/pylixm/django-mdeditor/blob/master/mdeditor_demo_app/templates/show.html
- https://github.com/pylixm/django-mdeditor/issues/7
- https://github.com/pylixm/django-mdeditor/issues/8

**Comment by icoder-new** [comment]
> The text in the database is saved in markdown format, and the front-end display needs to be rendered by yourself.Here are some examples for reference.
> 
> * https://github.com/pylixm/django-mdeditor/blob/master/mdeditor_demo_app/templates/show.html
> * #7
> * #8

Thanks I'll try to make front-end! :heart:

**Comment by sdiggles** [comment]
How can I change to the dark theme or add my own styles this way?
