### ISSUE TITLE
使用OSS存储的时候图片无法正常显示

### ISSUE THREAD

**Issue by hxp-plus** [pylixm/django-mdeditor#112]
![2020-07-25 (5)](https://user-images.githubusercontent.com/9010121/88447900-dd20f000-ce6a-11ea-9ea4-594847b96837.png)
如图所示，我使用了阿里云的OSS存储，然后图片无法正常显示。
原因是图片在OSS上，这个img的src应该是“<OSS地址>/media/<图片地址>”。

**Comment by pylixm** [comment]
这里应该是你设置的 media_url 的问题，设置的时候应该加上你 oss  的地址。

**Comment by hxp-plus** [comment]
谢谢，我试试
