### ISSUE TITLE
Language unable to set to English

### ISSUE THREAD

**Issue by tywin1104** [pylixm/django-mdeditor#113]
Hi! This is amazing work. However I was unable to set language to English under Django's setting
`'languaje': 'en'  # zh / en / es`
I suppose this should set the global language to English. However hovering UI elements in the editor still showing up Chinese characters. Thank you!

**Comment by Wistral** [comment]
upstream(**editor.md** ) seems already support for English

https://github.com/pandao/editor.md/issues/404

When set `settings.MDEDITOR_CONFIGS['default']['language']='en'` and refresh my webpage,

I can't see a `en.js` to be loaded, which is needed to set language to English.


However, I find a way to solve, which directly use js to create an editor according to https://github.com/pandao/editor.md#create-a-markdown-editor

And add some modification to script

```js
<script type="text/javascript">
    $(function () {
        var path = "/static/editor.md/languages/en";
        // not `var path = "/static/editor.md/languages/en.js";`
        // which will cause a load `en.js.js` 404 problema
        editormd.loadScript(path, function () {
            editor.lang = editormd.defaults.lang;
            editor.recreate();
        });
        var editor = editormd("editor", {
            width: "1000px",
            height: "400px",
            float: "right",
            // markdown: "xxxx",     // dynamic set Markdown text
            path: "/static/editor.md/lib/"  // Autoload modules mode, codemirror, marked... dependents libs path
        });
        
    });
</script>
```


#### Effect
![image](https://user-images.githubusercontent.com/40349434/90091681-929fde80-dd59-11ea-82fc-f36c8749f5dd.png)


Anyway, it's a walk-around. maybe django-mdeditor needs to fix bugs 


(eg. `languaje` typo in [README](https://github.com/pylixm/django-mdeditor/blob/master/README.md))😅

**Comment by tywin1104** [comment]
@Wistral  Thanks for your answer. Actually this is caused by the typo you mentioned above it was mistyped to `languaje`, switch this to `language` works with my current setting
`'language': 'en'  # zh / en / es`
