### ISSUE TITLE
我无法将图像保存在heroku的cloudinary中。 我该怎么办？

### ISSUE THREAD

**Issue by takuya254** [pylixm/django-mdeditor#114]
我向Django制作的博客应用程序介绍了django-mdeditor。
我能够将图像保存在本地。 部署到heroku也很成功。 但是，无法将其保存在cloudinary中。
如果有解决方案，请告诉我。
谢谢。

**Comment by luzp-git** [comment]
修改上传图片的路由，指向你自己实现的上传视图函数上
```python
path('mdeditor/uploads/', 你的视图函数, name='uploads')
```
然后，自己去实现这个上传的功能就好了

**Comment by pylixm** [comment]
项目没有适配各种云存储，可按 @luzp-git 的方法来自己实现。我暂时先关闭这个issue 了，有问题可重新打开。
