### ISSUE TITLE
Refused to display 'xxx' in a frame because it set 'X-Frame-Options' to 'deny'.

### ISSUE THREAD

**Issue by Unnamed-py** [pylixm/django-mdeditor#115]
添加图片时控制台出现"Refused to display 'https://unnamedpy.pythonanywhere.com/mdeditor/uploads/?guid=1598527418246' in a frame because it set 'X-Frame-Options' to 'deny'."
环境：django 3.1, python 3.8

**Comment by pylixm** [comment]
X_FRAME_OPTIONS = 'SAMEORIGIN'  

django 3.0+ 需要加这个参数，它默认是 deny的。文档说明中有提到。
