### ISSUE TITLE
图片已经成功上传到目标文件夹内，可是前端拿不到该图片的url

### ISSUE THREAD

**Issue by 1433522** [pylixm/django-mdeditor#117]
可以成功上传本地图片
![Screenshot from 2020-09-14 23-02-54](https://user-images.githubusercontent.com/58353114/93103183-e7c76b00-f6de-11ea-823d-544f8364f942.png)
但是无法自动获取地址
![Firefox_Screenshot_2020-09-14T15-02-39 177Z](https://user-images.githubusercontent.com/58353114/93103283-062d6680-f6df-11ea-8ea8-f0816dd54988.png)

**Comment by 1433522** [comment]
@pylixm

**Comment by 1433522** [comment]
求大佬指点

**Comment by pylixm** [comment]
大概率是参数 ` X_FRAME_OPTIONS = 'SAMEORIGIN' ` 问题，添加参数再试试。

**Comment by 1433522** [comment]
> 大概率是参数 `X_FRAME_OPTIONS = 'SAMEORIGIN'` 问题，添加参数再试试。

这个在哪个文件添加呢？

**Comment by pylixm** [comment]
settings.py

**Comment by 1433522** [comment]
> settings.py
谢谢大佬，已经成功！
