### ISSUE TITLE
How to change tooltip language?

### ISSUE THREAD

**Issue by mpbunch** [pylixm/django-mdeditor#118]
within settings.py I changed the mdeditor_configs = {...}
'language': 'en'  # zh / en / es 

But this has no impact on the tooltip language, or the timestamp text.
Is there something else that needs to be changed?

**Comment by pylixm** [comment]
Can you elaborate on the tooltip language and the timestamp text of that place?

**Comment by mpbunch** [comment]
* When you hover any of toolbar icons, the language does not seem to change.
![image](https://user-images.githubusercontent.com/7864344/93775838-e4594580-fbf0-11ea-8016-fbaa168d79b0.png)

* When you try to use the datetime feature in the navigation bar, the timestamp is not in the correct language.
![image](https://user-images.githubusercontent.com/7864344/93776298-6fd2d680-fbf1-11ea-95b3-74393f8e637e.png)

**Comment by pylixm** [comment]
This is my test case：
![image](https://user-images.githubusercontent.com/15826317/93837548-1930cf80-fcb9-11ea-805c-8f7756c11cea.png)

I am using version 0.1.19. Your problem has not reproduced.
It is recommended to check whether the static files related to your language have been loaded. Can you provide a reproducible example? Let me debug it.

**Comment by pylixm** [comment]
I haven't responded for a long time, you can reopen the issue if necessary.
