### ISSUE TITLE
在django2.1+python3.6环境下报错？

### ISSUE THREAD

**Issue by Green-unicorn** [pylixm/django-mdeditor#12]
我本地用的django2.1+python3.6环境，使用时直接报错，不知是否对django2.1有兼容性问题？

**Comment by pylixm** [comment]
可否将错误贴出。`django-mdeitor`代码非常简单，可尝试将错误修正后提交PR~

**Comment by hundanLi** [comment]
python3.6 + django2.0出错：

 from mdeditor.fields import MDTextField
ModuleNotFoundError: No module named 'mdeditor.fields'

**Comment by Green-unicorn** [comment]
下面是我的报错截图，之前上传文件失败，要开代理才能上传，抱歉
![qq](https://user-images.githubusercontent.com/30412878/44049734-7e32f748-9f67-11e8-882c-cda79a90ee55.png)

**Comment by rotateX** [comment]
网上找了下
![_20180825195927](https://user-images.githubusercontent.com/13715153/44618046-6a372500-a8a1-11e8-8793-b75ebb587d91.png)
这个文件
`
boundfield.py中的def as_widget方法93行
源
return widget.render(
   name=self.html_initial_name if only_initial else self.html_name,
   value=self.value(),
   attrs=attrs,
   renderer=self.form.renderer,
)
修改为：
return widget.render(
   name=self.html_initial_name if only_initial else self.html_name,
   value=self.value(),
   attrs=attrs,
   # renderer=self.form.renderer,
)
return force_text(html)
`

**Comment by pylixm** [comment]
Fixed, please try to use the latest version.
