### ISSUE TITLE
How to rebuild editormd.min.js file ?

### ISSUE THREAD

**Issue by ezawadzki** [pylixm/django-mdeditor#121]
Hi,

I would like to add a custom javascript plugin. What is the best way to do that ?
How can I rebuild editormd.min.js as there's no the original gulp file from [editor.md](https://github.com/pandao/editor.md).

Thanks for help.

Emilie

**Comment by pylixm** [comment]
sorry,I also don't have source files. Editor.md hasn't been updated for a long time, there should be other versions in the list of issues you can find.

**Comment by ezawadzki** [comment]
The source file are available in [editor.md](https://github.com/pandao/editor.md). There is a [gulp](https://github.com/pandao/editor.md/blob/master/Gulpfile.js) file available to help to watch or build sources. Maybe we should review the architecture of the front part ?

**Comment by pylixm** [comment]
If there is no reply for a long time, it is temporarily closed and can be reopened if necessary.
