### ISSUE TITLE
后台使用编辑器插入表情预览时正常显示，但打开网页后前端并未渲染成功

### ISSUE THREAD

**Issue by Cuber-final** [pylixm/django-mdeditor#126]

**Comment by qlzzriyue** [comment]
前端要渲染，需要把表情放到指定的static对应的目录中，然后在前端的`editormd.js`或`editormd.min.js`（你前端引入的哪个，就修改哪个）中搜索对应代码，这里以emoji为例：搜索`editormd.emoji`，第一处即可看到代码如下：
```python
editormd.emoji = {
        path  : "https://www.webpagefx.com/tools/emoji-cheat-sheet/graphics/emojis/",
        ext   : ".png"
    };
```
假设在前端的静态资源文件已经搞定，只要在这里把`path`的值更换为emoji的目录路径就行了。

**Comment by pylixm** [comment]
长时间没有反馈，如果如需要可以重开。
