### ISSUE TITLE
Can I add my localization file?

### ISSUE THREAD

**Issue by uselessvevo** [pylixm/django-mdeditor#131]
I've translated editor's localizaation file to my native, then I've collected static files (`manage.py collectstatic`), changed `MDEDITOR_CONFIGS -> 'language'` to 'ru' but editor switched to default chinese language.

What did I do wrong?

**Comment by uselessvevo** [comment]
Okay, there is the first solution. You need to modify markdown.html in here: https://github.com/pylixm/django-mdeditor/blob/master/mdeditor/templates/markdown.html#L41

Here is the code:

```html
{% block load_js %}
<script src={% static 'mdeditor/languages/'|add:config.language|add:'.js' %}></script>
{% endblock %}
```

And it will work. But I don't really like how you implemented localization in plugins. Maybe, I will modify it too.

**Comment by pylixm** [comment]
You can try to submit a PR for your own native, like PR https://github.com/pylixm/django-mdeditor/pull/104

**Comment by pylixm** [comment]
If there is no reply for a long time, it is temporarily closed and can be reopened if necessary.
