### ISSUE TITLE
如何限制编辑器的宽度

### ISSUE THREAD

**Issue by lzjun567** [pylixm/django-mdeditor#134]
默认情况下，编辑器宽度是屏幕的宽度，如何设置宽度使其自动换行，而不是出现滚动条

![image](https://user-images.githubusercontent.com/3820941/113946592-5a469680-983b-11eb-91ee-2d87005d63e3.png)

**Comment by lzjun567** [comment]
找到了配置的参数，将lineWrapping设置为True即可
```
MDEDITOR_CONFIGS = {"default":  "lineWrapping": True}}
```

**Comment by pylixm** [comment]
感谢反馈
