### ISSUE TITLE
What is the best way to override all the styles?

### ISSUE THREAD

**Issue by osean-man** [pylixm/django-mdeditor#136]
I am trying to customize the styles and can't seem to figure out the best approach. Is there a way to allow for skinning the theme or is it just dark/light and that's it? If it is, where can I customize or override the dark theme styles?

**Comment by qlzzriyue** [comment]
You need to find the `editormd.preview.css` file, reference it in the needed pages, and then modify the style of this css file. If the front-end of the page wants to follow the `django-mdeditor` display, you only need to introduce this css file, other functions are driven by `.js` files (for example: `editormd.js`, `prettify.min.js`, etc.).
> Note that your site's original css styles may conflict with the editor's css styles.

**Comment by pylixm** [comment]
There has been no feedback for a long time, and it can be reopened if necessary.
