### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by hundanLi** [pylixm/django-mdeditor#14]
When I upload a picture which contains Chinese character in its name, it throw an Exception like this:

[wsgi:error]  File "/var/www/venv/lib/python3.6/site-packages/mdeditor/views.py", line 64, in post
[wsgi:error]    with open(os.path.join(file_path, file_full_name), 'wb+') as file:
 [wsgi:error] **UnicodeEncodeError**: 'ascii' codec can't encode characters in position 52-55: ordinal not in range(128)

**Comment by seekun** [comment]
$: export LC_ALL=C.UTF-8
$: export LANG=C.UTF-8
Type them to terminal, then problem sovled.

This system supports the C.UTF-8 locate which is recommended.
You might be able to resolve your issue by exporting the following environment variables:

export LC_ALL=C.UTF-8
export LANG=C.UTF-8

**Comment by pylixm** [comment]
@hundanLi  This situation should be related to the system code, whether the method provided by @seekun  has been solved?

**Comment by seekun** [comment]
My problem has been solved. 
When I use OS X system, there is no problem.
But when I install your package with pip in Ubuntu, it raised 'UnicodeEncodeError'. 
Then I try to use `pipenv install django-mdeditor` to install your package, pipenv also raise the same error and pipenv provide any advice to sovle this problem. 
```
$: export LC_ALL=C.UTF-8
$: export LANG=C.UTF-8
```
After executing the two instructions, the problem been solved.
