### ISSUE TITLE
GitHub emoji无法展示

### ISSUE THREAD

**Issue by Arithmeticjia** [pylixm/django-mdeditor#144]
找不到emoji资源

**Comment by qlzzriyue** [comment]
自己下载emoji的png图片文件夹，放置在自定义的目录，然后找到前端引用的`editormd.js`，搜索`editormd.emoji`，修改它的`path`路径即可。
这样可以保证前端可以正常预览。
后端同理，但是需要找到`django-mdeditor`库文件中的`editormd.min.js`文件，搜索和修改同样的内容即可。

**Comment by Arithmeticjia** [comment]
django-mdeditor这个库我本地怎么找不到啊，只有django_mdeditor-0.1.18.dist-info这个

**Comment by qlzzriyue** [comment]
> django-mdeditor这个库我本地怎么找不到啊，只有django_mdeditor-0.1.18.dist-info这个

一般情况下，在你的虚拟环境中安装后，在虚拟环境的目录下就可以找到。
例如：`虚拟环境目录\Lib\site-packages\mdeditor`，其中`mdeditor`就是该库的文件夹。

**Comment by pylixm** [comment]
长时间没有反馈，如果如需要可以重开。
