### ISSUE TITLE
Linking with GCS changes the PATH for retrieving static files.

### ISSUE THREAD

**Issue by kgmproject** [pylixm/django-mdeditor#147]
I have created an application with the following configuration.
- Django(mdeditor)
- GCE/GCS

When I go to GCS to get the following file from the admin panel, the GCS API key is inserted in the middle of the PATH and I cannot get the static file.

```
https://storage.googleapis.com/t<bucket name>/mdeditor/js/lib/?<GCS API key>codemirror/addon/search/matchesonscrollbar.css
```

The following is the PATH to go get the file that we are assuming.
```
https://storage.googleapis.com/t<bucket name>/mdeditor/js/lib/codemirror/addon/search/matchesonscrollbar.css?<GCS API key>
```

I don't know if it's something wrong with my configuration or if it's caused by the following code.
```
b.loadCSS(g.path + "codemirror/addon/search/matchesonscrollbar"))),
```

By the way, I have the same problem with both js/css.

I am Japanese, so I apologize for my poor English.
Thank you very much for your help.

**Comment by pylixm** [comment]
There has been no feedback for a long time, and it can be reopened if necessary.
