### ISSUE TITLE
Ubuntu compile error

### ISSUE THREAD

**Issue by leo493852107** [pylixm/django-mdeditor#15]
When I want to develop in Ubuntu, raise some errors, could you pls help?

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 3491: ordinal not in range(128)
```

![image](https://user-images.githubusercontent.com/9987499/44028333-1a9f5112-9f2c-11e8-91b6-81b4726ab2ef.png)

**Comment by seekun** [comment]
I faced the same problem. And I solved it. Maybe you can try this way too.
> `sudo pip install --user django-mdeditor`
If terminal prompt `locale.Error: unsupported locale setting`, you should type `export LC_ALL=C` and try again!

**Comment by seekun** [comment]
$: `export LC_ALL=C.UTF-8`
$: `export LANG=C.UTF-8`
Type them to terminal, then problem sovled.

> This system supports the C.UTF-8 locate wihci is recommended.
You might be able to resolve your issue by exporting the folling enviroment variables:

 export LC_ALL=C.UTF-8
    export LANG=C.UTF-8

**Comment by pylixm** [comment]
Has it been resolved?

**Comment by leo493852107** [comment]
> Has it been resolved?

Yes, thanks!
