### ISSUE TITLE
无法生成插件

### ISSUE THREAD

**Issue by redcican** [pylixm/django-mdeditor#155]
按照installation的说明下载安装，在渲染的时候还是生成django textarea, 在浏览器的console中报错

`(index):232 Uncaught ReferenceError: $ is not defined
    at 127.0.0.1/:232`

我使用的JQuery版本:
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
Django 版本:
Django==3.2.9

请问有人知道为什么吗?

**Comment by pylixm** [comment]
不需要单独的再引入jquery的库，模块里已经引入了。你这种错误，大概率是js冲突导致，可尝试添加如下代码解决，或者编辑器单独的在一个html页面。

```javascript

jQuery.noConflict();                //  将变量$ 让给模块jquery
jQuery(function(){                    // 自己引入的使用jQuery 调用
    jQuery("p").click(function(){
        alert( jQuery(this).text() );
         .... 
    });
});
```

**Comment by pylixm** [comment]
长时间没有反馈，需要的话可以重开这个issue。
