### ISSUE TITLE
How can I display formulas using latex?

### ISSUE THREAD

**Issue by astaka-pe** [pylixm/django-mdeditor#156]
**Requirements**
```
Django==3.2.5
django-mdeditor==0.1.18
Markdown==3.3.4
```
___
According to your [Quick start](https://github.com/pylixm/django-mdeditor#quick-start), I have tried to display formulas in a webpage.

Although a formula described in latex can be displayed in an admin page, 
<img width="1046" alt="スクリーンショット 2022-01-15 16 20 54" src="https://user-images.githubusercontent.com/64598460/149613366-168462c7-0ff9-451a-a58a-79add6e5b930.png">

it cannot be displayed appropriately in a webpage.
<img width="611" alt="スクリーンショット 2022-01-15 16 21 46" src="https://user-images.githubusercontent.com/64598460/149613402-00d33cb2-5cfd-4d5c-8eb9-310f0ff03861.png">

What kind of things do you think could be the cause?

**Comment by pylixm** [comment]
长时间没有回应，如有需要可再次开启本issue。
