### ISSUE TITLE
配置MDEDITOR_CONFIGS 必须全配，不然会报错，但我就想配置几个选项

### ISSUE THREAD

**Issue by tsoil** [pylixm/django-mdeditor#16]

**Comment by pylixm** [comment]
MDEDITOR_CONFIGS 这个配置是支持单个配置的，可否把你配置贴出来看下。

**Comment by tsoil** [comment]
MDEDITOR_CONFIGS = {
    'default': {
        'width': '90% ',  # Custom edit box width
        'heigth': 500,  # Custom edit box height
    }
}
当我只想改变编辑的大小，这个时候图片上传会报错
KeyError: 'upload_image_formats'

**Comment by pylixm** [comment]
已修复，请使用最新版本[v0.1.8](https://github.com/pylixm/django-mdeditor/tree/v0.1.8)
