### ISSUE TITLE
进入文章编辑页面console报错editormd.min.js:1 Uncaught TypeError: f.find(...).flowChart is not a function

### ISSUE THREAD

**Issue by flyly0755** [pylixm/django-mdeditor#162]
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/45039060/162554605-3ebb2dbb-1a60-4abb-b9ad-18c2b6e01d9e.png">

**Comment by pylixm** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by pylixm** [comment]
@flyly0755  你是用的版本是哪个？做过什么修改吗？

**Comment by flyly0755** [comment]
> <img alt="image" width="1435" src="https://user-images.githubusercontent.com/45039060/162554605-3ebb2dbb-1a60-4abb-b9ad-18c2b6e01d9e.png">

用的是最新的0.1.20版本，未做任何改动；admin未用django默认的，换成了simpleui

**Comment by pylixm** [comment]
建议单独一个 html 页面放 editor ，有可能是依赖的js 和 simpleui 的冲突。

**Comment by pylixm** [comment]
长时间未恢复，暂时关闭。若有需要可重新开启。
