### ISSUE TITLE
django 后台可以上传图片，前台链接没有加上base_dir

### ISSUE THREAD

**Issue by whk-newbie** [pylixm/django-mdeditor#164]
django 后台上传图片成功，保存后再次也可以加载图片
![1652105549(1)](https://user-images.githubusercontent.com/67769711/167431021-57ecd3f2-478e-40fb-b7af-3bac78bf0b2e.png)

使用MarkDown库对文本数据渲染成html后，文本无问题，图片链接无base_dir
![1652105645(1)](https://user-images.githubusercontent.com/67769711/167431008-aa07dc84-8031-4306-9be9-eb1ed147843e.png)
(尝试取消markdown渲染成html后依旧无basedir)

前端网页文章内容的图片无法显示

![1652105721(1)](https://user-images.githubusercontent.com/67769711/167431164-664ee30c-42e9-48dd-9c0a-072b357141dc.png)

手动在url处添加base_dir后可访问到图片
![1652106411(1)](https://user-images.githubusercontent.com/67769711/167431757-858b2670-7046-4aff-81b2-89eacebfd17a.png)

相关setting
![1652106438(1)](https://user-images.githubusercontent.com/67769711/167431904-20801b81-1e45-4474-8e49-9195e532457c.png)

![1652106620(1)](https://user-images.githubusercontent.com/67769711/167432496-807d2153-e5f5-4619-aa7d-9d58db0fc99a.png)

requirement
  ```
Django==4.0
  django-filter==21.1
  django-mdeditor==0.1.20
  django-simpleui==2022.1
  djangorestframework==3.13.1
  Markdown==3.3.6
```

**Comment by glinxx** [comment]
我也遇到这个问题，前后端分离时，这个相对图片地址就显示不了。有没有什么好的解决方法，打算在序列化时自动补全完整的url

**Comment by whk-newbie** [comment]
> 我也遇到这个问题，前后端分离时，这个相对图片地址就显示不了。有没有什么好的解决方法，打算在序列化时自动补全完整的url
我后面先放下这个问题了，我部署到服务器上的时候，前面创建的测试文字内图片文章里图片可以显示🤣，但是又出现了新问题，就是我没法上传图片了，不过这个应该时我nginx路径的配置问题；你可以参考下

**Comment by whk-newbie** [comment]
@glinxx 
> 我也遇到这个问题，前后端分离时，这个相对图片地址就显示不了。有没有什么好的解决方法，打算在序列化时自动补全完整的url
我后面先放下这个问题了，我部署到服务器上的时候，前面创建的测试文字内图片文章里图片可以显示🤣，但是又出现了新问题，就是我没法上传图片了，不过这个应该时我nginx路径的配置问题；你可以参考下

**Comment by pylixm** [comment]
@glinxx  @whk-newbie  

你们这个问题是 django 自身静态文件的设定，当  debug = True 时，django 静态文件会去找你配置的  media_url 参数的路径里找，比如下边这样：

![image](https://user-images.githubusercontent.com/15826317/182107751-e3952d52-c6df-4bbd-9332-87f2634486c1.png)

当debug 设置为 False 时，django 就不自动处理静态文件了，这时需要我们自己搭建一个 nginx 等其他静态文件服务。

生产环境，Django 前一般都会挂一个nginx 服务来处理静态文件，collectstatic 将静态文件收集到一个目录，将改目录指定到一个路由即可。 更多你可以参考我这个项目： https://github.com/pylixm/docker-django-demo/blob/docker-compose-production2/compose/nginx/nginx.conf

**Comment by pylixm** [comment]
长时间没反馈，如还有问题可随时打开此issue。
