### ISSUE TITLE
Need english language support 

### ISSUE THREAD

**Issue by xeroticikot** [pylixm/django-mdeditor#165]
Is it possible to show tooltips in at least english language, if possible may even convert to other languages?

**Comment by pylixm** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by xeroticikot** [comment]
I'm sorry, didn't notice the language option in the config section. All good now!
