### ISSUE TITLE
是否能够在wgtail中使用

### ISSUE THREAD

**Issue by zhhangtaao** [pylixm/django-mdeditor#166]
最近用wgtail做了个公司网站，希望能使用[django-mdeditor](https://github.com/pylixm/django-mdeditor)，不知道使用起来有多大难度。
或者在django_cms中可以使用吗？  希望告知 ，非常感谢！

**Comment by azataiot** [comment]
后台使用肯定没有问题，就看你前台怎么配置了

**Comment by pylixm** [comment]
长时间没有回应，如有需要可再次开启本issue。
