### ISSUE TITLE
upload image - bug

### ISSUE THREAD

**Issue by zhenda-hub** [pylixm/django-mdeditor#177]
Why I got this when I upload image?
 Not Found: /mdeditor/uploads/

**Comment by pylixm** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by pylixm** [comment]
你可以按照文档步骤再仔细对照下，理论上不应该出现你这个错误。
