### ISSUE TITLE
建议添加渲染数据的template tags 或 filters

### ISSUE THREAD

**Issue by HB6H057** [pylixm/django-mdeditor#18]
这样可以充分显示集成实时的样式，最近在弄这个功能，如果不介意到时候可以提一个PR。

**Comment by pylixm** [comment]
没问题，欢迎提交~

**Comment by reBiocoder** [comment]
保存的数据库的文章，用什么渲染？  python自带的markdown好像渲染不了

**Comment by FY2008** [comment]
> 保存的数据库的文章，用什么渲染？ python自带的markdown好像渲染不了
我在类视图中是这样写的，可以渲染markdown。先安装markdown
`pip install markdown`
`
import markdown

def get_object(self, queryset=None):
        obj = super(ArticleDetailView, self).get_object()
        obj.viewed()
        obj.body = markdown.markdown(
            obj.body,
            extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',  # 代码高亮
                'markdown.extensions.toc',
            ]
        )
        self.obj = obj
        return obj
`

**Comment by pylixm** [comment]
长时间无反馈，如有需要可重开。
