### ISSUE TITLE
Hi, how can i change the language of the mdedior?

### ISSUE THREAD

**Issue by hfa2010** [pylixm/django-mdeditor#19]
Hi, i'm sorry if this is the wrong place but is it possible to change the language of the editors toolbar toolips?
I tried setting language in the MDEDITOR_CONFIGS in settings.py but it didn't work. LANGUAGE_CODE is also already set.

django-mdeditor is almost perfect for what i'm doing and the only thing stopping it from being perfect is this language problem.

**Comment by hfa2010** [comment]
Solved by editing the minified js

**Comment by Symonss** [comment]
> Solved by editing the minified js

How did you do it? I cant find that minified js anywhere in my files
