### ISSUE TITLE
显示有问题

### ISSUE THREAD

**Issue by 1049759078** [pylixm/django-mdeditor#2]
我按照博客和github上的使用步骤完成之后，在admin后台访问，结果如下
[](http://images.cnblogs.com/cnblogs_com/guigujun/1143402/t_%e9%94%99%e8%af%af.png)
http://images.cnblogs.com/cnblogs_com/guigujun/1143402/t_%e9%94%99%e8%af%af.png
我把github上的demo运行之后也是如上图这样

**Comment by pylixm** [comment]
同问题：https://github.com/pylixm/django-mdeditor/issues/1
