### ISSUE TITLE
本地测试图片上传没问题，但是部署无法其之后本地图片上传无法显示

### ISSUE THREAD

**Issue by reBiocoder** [pylixm/django-mdeditor#21]
本地测试图片上传没问题，但是部署无法其之后本地图片上传无法显示，请问这是什么原因啊，是ubuntu文件夹没有权限访问的原因吗

**Comment by tsoil** [comment]
首先查看是否有这个文件，如果有，查看url是否显示，如果不显示就是url的问题

**Comment by reBiocoder** [comment]
谢谢，解决了，是文件夹权限的问题
