### ISSUE TITLE
上传图片路径路径小bug

### ISSUE THREAD

**Issue by Y4er** [pylixm/django-mdeditor#24]
![image](https://user-images.githubusercontent.com/40487319/48968874-8711fe80-f030-11e8-869f-1ed79f763390.png)
![image](https://user-images.githubusercontent.com/40487319/48968876-8bd6b280-f030-11e8-8456-455414bd4d1f.png)
![image](https://user-images.githubusercontent.com/40487319/48968878-92652a00-f030-11e8-9b4c-af4f5848ae18.png)

**Comment by pylixm** [comment]
已修改，多谢贡献
