### ISSUE TITLE
该怎么关闭实时预览呢？

### ISSUE THREAD

**Issue by rongDang** [pylixm/django-mdeditor#25]
我想在前端评论使用mdeditor，但我不想让它出现实时预览，我该如何做，
还有该如何渲染那些emoji在前端显示，我的数据库已经设置为了utf8md4了，但是前端显示不了那些表情，可以告诉我该怎么做吗？

**Comment by pylixm** [comment]
抱歉，现阶段这些问题还没有很好的解决方案，暂时作为一个feature。也欢迎提交你的解决方案！

**Comment by jin544642965** [comment]
遇到同样的问题，编辑文档显示不出表情按钮
![image](https://user-images.githubusercontent.com/18446221/54270536-95256400-45ba-11e9-9828-34b892acdb8a.png)

**Comment by iHTCboy** [comment]
![image](https://user-images.githubusercontent.com/11418363/61031229-a60fa600-a3f1-11e9-8ef1-d976794e04e2.png)

```
this.unwatch();
```

@rongDang 暂时可以这个解决

**Comment by pylixm** [comment]
这个参数也可以：

```
watch: {{ config.watch|lower }}, // 关闭实时预览
```
