### ISSUE TITLE
上传有下划线的图片或者有些中文字体的图片会报错

### ISSUE THREAD

**Issue by reBiocoder** [pylixm/django-mdeditor#28]
怎么解决呢

**Comment by reBiocoder** [comment]
建议修改保存时候的文件名为随机数加时间加文件内容。

`
   ** save image
        import random
        new_file_name=random.randint(0,4897151534531)
        file_full_name = '%s_%s.%s' % (new_file_name,
                                       '{0:%Y%m%d%H%M%S%f}'.format(datetime.datetime.now()),
                                       file_extension)
        with open(os.path.join(file_path, file_full_name), 'wb+') as file:
            for chunk in upload_image.chunks():
                file.write(chunk)
`

这样就不会出现问题了

**Comment by pylixm** [comment]
@reBiocoder   可以提交个PR 。
