### ISSUE TITLE
安装出错

### ISSUE THREAD

**Issue by sangyunxin** [pylixm/django-mdeditor#3]
安装时出现错误：
![image](https://user-images.githubusercontent.com/32364921/37254361-74b7591c-2577-11e8-8219-7cfd89ca09ba.png)
怎么解决啊？这个编辑器很漂亮，想用。

**Comment by sangyunxin** [comment]
应该把setup.py中第五行改为：
`with open(os.path.join(os.path.dirname(__file__), 'README.md'), encoding='utf-8') as readme:`

提交了更改，希望采纳

**Comment by pylixm** [comment]
@sangyunxin   已修复，为兼容python2 把Readme中文改英文了。
