### ISSUE TITLE
django-mdeditor中引入的jquery与页面中的jquery版本冲突怎么办

### ISSUE THREAD

**Issue by jin544642965** [pylixm/django-mdeditor#36]

**Comment by jin544642965** [comment]
找到一种方法就是要注释掉site-packages/mdeditor/widgets.py中的jquery的引用，才成功。。有没别的方法还要改插件源码真麻烦
![image](https://user-images.githubusercontent.com/18446221/53868761-b40f7d80-4031-11e9-866c-44265bd9b026.png)
![image](https://user-images.githubusercontent.com/18446221/53868843-e1f4c200-4031-11e9-9905-bb5da85ce9c3.png)

**Comment by pylixm** [comment]
建议使用同版本的jquery
