### ISSUE TITLE
自动滚动到editor页面

### ISSUE THREAD

**Issue by yuanquan99** [pylixm/django-mdeditor#41]
当页面较长时, 进度条会自动滚动到editor处, 可以设置为不滚动吗

**Comment by pylixm** [comment]
可否提供个页面demo ，便于我调试。

**Comment by yuanquan99** [comment]
就是点开页面, 它会自动滚动到编辑器处; (不会制作动图呀)
editor.js中注释掉`this.setCodeMirror().setToolbar().loadedDisplay();`一行解决了

**Comment by iHTCboy** [comment]
@yuanquan99 我试了，好像不行呢？

**Comment by yuanquan99** [comment]
@pylixm 建议作者把这个默认定位到输入框取消..

**Comment by iHTCboy** [comment]
@pylixm 嗯，谢谢，我又找到了，原来有属性设置的，可以自己改一下，这个就不用改js文件，方便一些

![image](https://user-images.githubusercontent.com/11418363/61046864-c13dde00-a410-11e9-905e-89dd120d62bd.png)
