### ISSUE TITLE
Change menu language

### ISSUE THREAD

**Issue by thimy** [pylixm/django-mdeditor#42]
Hi,

I installed the package and it works all fine, except that all menus (like the upload menu) are all in chinese.

I saw that someone already addressed a similar issue but I can't figure out how to access the js file.

Thank you!

**Comment by pylixm** [comment]
I will add support later.

**Comment by pylixm** [comment]
already added , please use [v0.1.14](https://github.com/pylixm/django-mdeditor/releases/tag/v0.1.14) .
