### ISSUE TITLE
上传后的图片怎么管理？

### ISSUE THREAD

**Issue by leffss** [pylixm/django-mdeditor#44]
比如怎么删除（直接在服务器文件夹去删也太low了吧）？一张图片使用多次怎么获取URL（不可能每次都在使用过它的文章里面去复制URL过来吧。。。）？

**Comment by pylixm** [comment]
图片管理这块暂时没有涉猎，你有什么好的建议吗？

**Comment by leffss** [comment]
> 图片管理这块暂时没有涉猎，你有什么好的建议吗？

能不能定制admin后台管理图片呢

**Comment by pylixm** [comment]
可以这样处理，有时间处理下，实现简单维护，也欢迎提交PR。

**Comment by leffss** [comment]
> 可以这样处理，有时间处理下，实现简单维护，也欢迎提交PR。

哈哈，心有余而力不足，我只是python爱好者而已，苦逼运维一个

**Comment by rinscr3003** [comment]
可以考虑检验图片的md5，如果一样就不再次上传

**Comment by Ehco1996** [comment]
能不能开放一个关闭图片上传的配置？
