### ISSUE TITLE
image upload error, how to solve this problem?

### ISSUE THREAD

**Issue by vannesspeng** [pylixm/django-mdeditor#45]
after choose a picture , a error happend 

image-dialog.js:158 Uncaught DOMException: Blocked a frame with origin "http://39.108.225.222:8888" from accessing a cross-origin frame.
    at HTMLIFrameElement.uploadIframe.onload (http://39.108.225.222:8888/static/mdeditor/js/plugins/image-dialog/image-dialog.js:158:128)

this problem only occurs when i release it in centos，it is normal in local。

**Comment by pylixm** [comment]
Before you release the code, make sure you configure your static server。

**Comment by pylixm** [comment]
No response, temporarily closed.

**Comment by pylixm** [comment]
No response, temporarily closed.
