### ISSUE TITLE
您好，想咨询一下，如果调整输入框的高度

### ISSUE THREAD

**Issue by AllenBigBear** [pylixm/django-mdeditor#46]
您好，我是您这个包的使用者，谢谢您的开源。
目前我在使用中碰到了一些问题想请教一下。
我在用python编写django程序，在setting中想调整edit box的尺寸，但是调整宽度可以生效
高度的调整，改了参数以后没有反应，能否帮忙看一下？谢谢

参数如下：
        'width': '100% ',  # Custom edit box width
        'heigth': 500,  # Custom edit box height

这个500我无论如何调整，都没有用.

**Comment by pylixm** [comment]
这个问题已修改，之前单词拼错了。见这个issue：https://github.com/pylixm/django-mdeditor/issues/26

**Comment by AllenBigBear** [comment]
> 这个问题已修改，之前单词拼错了。见这个issue：#26
> 可更新下版本，或检查下是否有同样错误。

啊，ok，好的，谢谢了！我自己也没注意
