### ISSUE TITLE
Background and text color of fieldsets title was overwrited

### ISSUE THREAD

**Issue by fdddf** [pylixm/django-mdeditor#49]
Background and text color of fieldsets title was overwrited, 
![Screen Shot 2019-07-08 at 00 38 31](https://user-images.githubusercontent.com/2045357/60771350-61e28400-a119-11e9-986a-1922532e42f4.png)

**Comment by pylixm** [comment]
already fixed in new version [v0.1.15](https://pypi.org/project/django-mdeditor/)
