### ISSUE TITLE
django前端用什么python包去解析啊

### ISSUE THREAD

**Issue by libyoung** [pylixm/django-mdeditor#5]
前端markdown解析和后台编辑预览的不一样

**Comment by pylixm** [comment]
可参考editor.md官方渲染样例:http://pandao.github.io/editor.md/examples/html-preview-markdown-to-html.html

**Comment by pylixm** [comment]
python后端解析样式和编辑器实时预览不通，建议前端使用editor.md原生解析。

**Comment by libyoung** [comment]
前端有没有ediror.md原生解析的python包

**Comment by pylixm** [comment]
这个没有，可以考虑搞下。等我有空了这个简单的例子。

**Comment by FormatToday** [comment]
您好，前端怎样不用form渲染出来

**Comment by pylixm** [comment]
@FormatToday  @libyoung   已添加前端渲染实例 ：https://github.com/pylixm/django-mdeditor/blob/master/mdeditor_demo_app/templates/show.html  

不过建议使用 [mistune](https://github.com/lepture/mistune) 后端渲染，editor.md 已经好久没有更新了~

**Comment by libyoung** [comment]
感谢🙏

发自我的 iPhone
