### ISSUE TITLE
求关闭实时预览和截图粘贴的功能！ 

### ISSUE THREAD

**Issue by iHTCboy** [pylixm/django-mdeditor#51]
望大佬有空维护更新吗？

**Comment by iHTCboy** [comment]
关闭实时预览暂时可以这样解决：`this.unwatch();`

![image](https://user-images.githubusercontent.com/11418363/61031272-c0498400-a3f1-11e9-898c-8170c602d34e.png)

**Comment by pylixm** [comment]
感谢反馈！
