### ISSUE TITLE
大佬，问一下内容渲染到html模板，有没有提供接口，可以显示跟预览一样的样式啊？

### ISSUE THREAD

**Issue by iHTCboy** [pylixm/django-mdeditor#55]
大佬，问一下内容渲染到html模板，有没有提供接口，可以显示跟预览一样的样式啊？

先感谢，大佬有空回复一下，望指教，新手一枚~

**Comment by pylixm** [comment]
可参考下这个demo： https://github.com/pylixm/django-mdeditor/blob/master/mdeditor_demo_app/templates/show.html

**Comment by iHTCboy** [comment]
@pylixm 完美，感谢大佬！
