### ISSUE TITLE
不支持django 2.0吗？

### ISSUE THREAD

**Issue by fgd-haha** [pylixm/django-mdeditor#6]
运行pip install django-mdeditor  给我吧django2.0卸载了，安了django1.11 
太太太坑了

**Comment by FormatToday** [comment]
对，我也是这样

**Comment by pylixm** [comment]
@fgd-haha  @FormatToday   2.0和1.11 主要区别是路由那里，其他地方没有影响。可自行修改，或等待新版本发布。

**Comment by edenzyk** [comment]
开发者能说清楚点吗  萌新一脸懵逼

**Comment by pylixm** [comment]
@edenzyk  django2.0 和1.11 在使用本库的时候，现在已知的问题是，url 路由的写法问题。2.0 是使用 `path ` 函数来解析路由，1.11 和之前的版本都是使用 `url` 。这个地方你可以自己修改下，在安装本模块的时候，若不想卸载django2.0 ，可把 [文件setup.py](https://github.com/pylixm/django-mdeditor/blob/master/setup.py) 中的以下代码注释掉，再使用 `python setup.py install ` 安装。
```python
install_requires=[
        'django==1.11.10',
    ],
```

**Comment by pylixm** [comment]
已增加对 django 2.0 的支持，见:[commit](https://github.com/pylixm/django-mdeditor/commit/6904ff011a0417350b362fc3b74f2a76e2f3794d)
