### ISSUE TITLE
关于@功能匹配不正确的疑问

### ISSUE THREAD

**Issue by iHTCboy** [pylixm/django-mdeditor#60]
用editormd.markdownToHTML()渲染后，@正则时，总是不能正确匹配

@后没有空格，直接换行：
```
@HTC-boy
换行
```

@后空格:
```
@HTC-boy 空格
```

@后空格，直接换行：
```
@HTC-boy
换行
```

然后用editormd.markdownToHTML()渲染后，发现结果:

1、 `https://www.xxxx.com/HTC-boy<br>`
2、  `https://www.xxxx.com/HTC-boy`
3、 `https://www.xxxx.com/HTC-boy<br>`

多了空格符号:`<br>`。

因为我们用的@用户名可能有其它字符，我改了正则为`/@(\S+)(?=<br>)+|@(\S+)/g;`

所以，不知道是不是一个bug？

**Comment by pylixm** [comment]
应该是个bug，欢迎提交PR。或直接到 editor.md 官方提交。
