### ISSUE TITLE
编辑器内容默认值

### ISSUE THREAD

**Issue by lzxzy** [pylixm/django-mdeditor#62]
您好
请问如何将已有的内容填充进编辑其中，
例如在修改已有的文章的时候，打开编辑器，已经有的文章内容可以填充在编辑器的编辑窗口中

**Comment by rinscr3003** [comment]
django后台默认情况下是可以自动填充的，不存在该问题。

**Comment by lzxzy** [comment]
> django后台默认情况下是可以自动填充的，不存在该问题。

后台填充没问题，是在前端调用的时候，就是表单哪里，比如我要渲染一个update页面，然后默认填充历史数据，但是实际显示里面是空的

**Comment by lzxzy** [comment]
同时我在浏览器调试的时候有这个错误，可以麻烦您看一下是什么原因么
`editormd.min.js:1 Uncaught TypeError: f.find(...).flowChart is not a function
    at init.flowChartAndSequenceDiagramRender (editormd.min.js:1)
    at editormd.min.js:1`

**Comment by lzxzy** [comment]
> 您好
> 请问如何将已有的内容填充进编辑其中，
> 例如在修改已有的文章的时候，打开编辑器，已经有的文章内容可以填充在编辑器的编辑窗口中

关于前端update的时候，默认填充搞定了
即在前端使用的时候，我们实际是通过表单调用的
`{% load staticfiles%}
<! DOCTYPE html>
<html lang = "en">
    <head>
        <meta http-equiv = "Content-Type" content = "text / html; charset = utf-8" />

    </ head>
    <body>
        <form method = "post" action = "./">
            {% csrf_token%}
            {{form.media}}
            {{form.as_p}}
            <p> <input type = "submit" value = "post"> </ p>
        </ form>
    </ body>
</ html>`

因此要在渲染该模板的视图函数里，对表单使用数据绑定
例如：在某view.py文件里
`
def article_update(request, id):
    ......
    if request.method == 'GET':
        article_post_form = ArticlePostForm({'body':article.body})  // 这里的article_post_form 是一个表单实例，其中 body属性做了数据绑定默认值为文章历史数据article.body
`
