### ISSUE TITLE
Localization issue

### ISSUE THREAD

**Issue by dphans** [pylixm/django-mdeditor#63]
Can I change language/locale in editor settings?
I think default locale has been set to `zh-CN`, so the editor displaying Chinese text instead of English.
How can I change this text?

<img width="256" alt="Screen Shot 2019-09-30 at 10 25 14 AM" src="https://user-images.githubusercontent.com/12996976/65847676-b722e000-e36c-11e9-9da2-b9a8c32566bf.png">

**Comment by dphans** [comment]
OK, I found the settings in source code. It need to set `localization` into `en` to change locale into English.
Please update into documentation, thanks you!

**Comment by arsensokolov** [comment]
@dphans where is set `localization`?
