### ISSUE TITLE
添加图片使用本地上传，不能自动生成相应的图片地址

### ISSUE THREAD

**Issue by Krystal1010** [pylixm/django-mdeditor#64]

**Comment by pylixm** [comment]
可够提供下各库详细版本信息，及具体的报错信息。

**Comment by Krystal1010** [comment]
各库版本：
django==2.2.6
django-mdeditor==0.1.16
运行没有任何报错，图片可以在上传指定的文件夹里找到，数据库里也没有找到相应的图片地址。

**Comment by Krystal1010** [comment]
添加图片的另一种方式使用图片链接也会“图片地址不能为空的错”

**Comment by Krystal1010** [comment]
添加图片的另一种方式使用图片链接也会报“图片地址不能为空的错”。

**Comment by pylixm** [comment]
根据你的描述，本地上传没有返回图片地址还是没法确认具体问题。另一中直接使用连接方式，我也尝试了，错误是`editor.md `抛出的，貌似这两种方式不能同时出现。建议如下使用：
1、本地上传
2、使用 markdown 的图语法 `![](image url)`

**Comment by Krystal1010** [comment]
好的谢谢，markdown的图语法我测试过是可以正常使用的，我在找找问题
