### ISSUE TITLE
How to render the marked-down content?

### ISSUE THREAD

**Issue by alfarhanzahedi** [pylixm/django-mdeditor#67]
I have successfully integrated the editor in my Django application. Everything is working as expected, but I cannot find a way to render the mark-down content. 

I am using the editor in the admin-panel to store a rich markdown text. But, I cannot find a way to render it in the same way as mdeditor in the front-end. 

Any idea on how to achieve that?

**Comment by pylixm** [comment]
@alfarhanzahedi  You can refer this https://github.com/pylixm/django-mdeditor/issues/5
