### ISSUE TITLE
django3.0图片上传适配

### ISSUE THREAD

**Issue by alexTse824** [pylixm/django-mdeditor#69]
django2.x后台图片上传正常显示；

相同配置在django3.0后台上传图片前端控制台报错：
`Refused to display 'http://127.0.0.1:8000/mdeditor/uploads/?guid=1576638285513' in a frame because it set 'X-Frame-Options' to 'deny'.
image-dialog.js:158`

`Uncaught DOMException: Blocked a frame with origin "http://127.0.0.1:8000" from accessing a cross-origin frame. atHTMLIFrameElement.uploadIframe.onload(http://127.0.0.1:8000/static/mdeditor/js/plugins/image-dialog/image-dialog.js:158:129)`

图片正常上传至后端文件夹内，但前端图片地址栏无显示；
管理后台手动输入image url，图片渲染时后端报错Not Found；

**Comment by pylixm** [comment]
You need to add configuration X_FRAME_OPTIONS = 'SAMEORIGIN', django 3+ defaults to deny.
