### ISSUE TITLE
md 可以转成 html吗？

### ISSUE THREAD

**Issue by yqnku** [pylixm/django-mdeditor#7]
我想问一下，能够在后台将 markdown 转换成 html吗？因为我前端用的是 Angular，不是用 django 的模板引擎。以及插入的图片或者公式能不能居中呢？就像是 MWeb 那样，用 $ 包裹则是行内公式，用 $$ 包裹则是行间公式，对于图片，用 [-c] 则可以使图片居中。谢谢！

**Comment by pylixm** [comment]
1、对于html问题。mdeditor 自身带有转化的参数 `saveHTMLToTextarea `可以使保存时直接保存为html，但是我没有测试成功。
可使用以下折中办法：
- 第一种，保存的时候自己处理，参考[这里](https://github.com/pandao/editor.md/blob/master/examples/full.html#L191)。
- 第二种，在后台将markdown，渲染为html后再返回页面显示。

2、对于显示居中问题。这个本项目没有做限定和涉猎，可自定义css或使用mdeditor的显示css。针对你的建议比如加 $ 或 $$ 来控制显示方式，则属于渲染显示方面的了，后期可以考虑添加统一的显示控制。

如果你有时间的话，欢迎推送PR。
