### ISSUE TITLE
windows安装问题

### ISSUE THREAD

**Issue by 9death** [pylixm/django-mdeditor#71]
windows用pip安装总是报错
File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-8t5_9iaq\django-mdeditor\setup.py", line 5, in <module>
        long_description = readme.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 167: illegal multibyte sequence

**Comment by pylixm** [comment]
@9death  能否提供下你的python 版本和系统

**Comment by 9death** [comment]
我下载下来用setup.py装的，可以了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "DeanWu"<notifications@github.com&gt;; 
发送时间: 2019年12月27日(星期五) 中午1:37
收件人: "pylixm/django-mdeditor"<django-mdeditor@noreply.github.com&gt;; 
抄送: "盗号者→死"<826091200@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [pylixm/django-mdeditor] windows安装问题 (#71)




@9death  能否提供下你的python 版本和系统
