### ISSUE TITLE
0.1.17 Windows10下安装错误

### ISSUE THREAD

**Issue by liutianfang** [pylixm/django-mdeditor#72]
错误信息：
      File "C:\Users\xxx\AppData\Local\Temp\pip-install-yg2zdab3\django-mdeditor\setup.py", line 5, in <module>
        long_description = readme.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 167: illegal multibyte sequence

修改建议：
    
    with open(os.path.join(os.path.dirname(__file__), 'README.md')) as readme:

to：

    with open(os.path.join(os.path.dirname(__file__), 'README.md'), 'rb') as readme: 

    with open(os.path.join(os.path.dirname(__file__), 'README.md'), , encoding='UTF-8') as readme:

**Comment by Ameng404** [comment]
建议修改，我也遇到这个错误了

**Comment by Ameng404** [comment]
> 错误信息：
> File "C:\Users\xxx\AppData\Local\Temp\pip-install-yg2zdab3\django-mdeditor\setup.py", line 5, in
> long_description = readme.read()
> UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 167: illegal multibyte sequence
> 
> 修改建议：
> 
> ```
> with open(os.path.join(os.path.dirname(__file__), 'README.md')) as readme:
> ```
> 
> to：
> 
> ```
> with open(os.path.join(os.path.dirname(__file__), 'README.md'), 'rb') as readme: 
> 
> with open(os.path.join(os.path.dirname(__file__), 'README.md'), , encoding='UTF-8') as readme:
> ```

建议退0.1.16  ，亲测有效

**Comment by pylixm** [comment]
这个地方 python3 和python2 有冲突，我抽空做下适配，上边建议，可以暂时修复安装问题。

**Comment by szdytom** [comment]
0.1.16似乎不支持Django3+，坐等修复

**Comment by pylixm** [comment]
已修复
