### ISSUE TITLE
Django后台修改文章时编辑器内显示为html代码

### ISSUE THREAD

**Issue by hellokuls** [pylixm/django-mdeditor#78]
![image](https://user-images.githubusercontent.com/42165104/75619153-105c9d00-5bb3-11ea-895c-7bf37853ac53.png)

大佬求解决！！！

**Comment by pylixm** [comment]
编辑器设计的如此，如需添加html 代码可使用代码块，更多可参考 editor.md 的官方 demo: http://editor.md.ipandao.com/examples/index.html
