### ISSUE TITLE
在django前端模板中怎么显示渲染好的markdown？

### ISSUE THREAD

**Issue by Lethons** [pylixm/django-mdeditor#8]

**Comment by pylixm** [comment]
@Lethons    {{ markdown_html |safe}}  加这个 safe 过滤器

**Comment by Lethons** [comment]
我之前就是那样写的，但是没有出来。
我看了下数据库，发现markdown写的格式没有转换成html标签，而是我在后台编辑器写的是什么样，储存起来还是什么样。还有我用的是django2.06，不知道是否支持，因为我在安装这个包时，他将我的django换为了django1.11。

**Comment by pylixm** [comment]
它保存的就是markdown的格式的文本。需要自己渲染，可参考这个 [django前端用什么python包去解析啊](https://github.com/pylixm/django-mdeditor/issues/5)

**Comment by Lethons** [comment]
哦，明白了。我以为是和ckeditor一样。非常感谢你的回答。
