### ISSUE TITLE
Prevent users to see the editor 

### ISSUE THREAD

**Issue by seyedian** [pylixm/django-mdeditor#83]
First of all, thank you so much for your wonderful markdown editor.
Can you please help me out on below:
I do have access into mdeditor  in Admin, is there any way to only display preview to some users? I do not want others to be able to edit.

**Comment by pylixm** [comment]
You can use preview mode or only read mode, reference here : http://editor.md.ipandao.com/examples/html-preview-markdown-to-html.html 
or  http://editor.md.ipandao.com/examples/readonly.html
