### ISSUE TITLE
from django.conf.urls import url, include

### ISSUE THREAD

**Issue by KangKang-Wang** [pylixm/django-mdeditor#84]
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
...

urlpatterns = [
    ...
    url(r'mdeditor/', include('mdeditor.urls'))
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

`from django.conf.urls.static import static`和最后那段debug加上之后就可以显示图片了

_Originally posted by @Pandapan-Buaa in https://github.com/pylixm/django-mdeditor/issues/74#issuecomment-608496395_

这段加了还是没反应，本来就是加的啊，上传图片能到后端，但是前端页面不显示图片url，感觉是没回调

**Comment by Pandapan-Buaa** [comment]
我这里加了前端就正常显示了。。不太清楚你具体是什么情况。
他readme里没把html中的内容字段添加过滤器safe，不知道是不是这个原因，具体见`https://blog.csdn.net/duke10/article/details/81033686`

**Comment by pylixm** [comment]
可参考这个 https://github.com/pylixm/django-mdeditor/issues/74
