### ISSUE TITLE
我这里加了前端就正常显示了。。不太清楚你具体是什么情况。

### ISSUE THREAD

**Issue by KangKang-Wang** [pylixm/django-mdeditor#85]
我这里加了前端就正常显示了。。不太清楚你具体是什么情况。
他readme里没把html中的内容字段添加过滤器safe，不知道是不是这个原因，具体见`https://blog.csdn.net/duke10/article/details/81033686`

_Originally posted by @Pandapan-Buaa in https://github.com/pylixm/django-mdeditor/issues/84#issuecomment-608504752_

不是这个原因，我在Django的admin里面操作的，不存在模板标注safe的问题，你是Django多少呀

**Comment by Pandapan-Buaa** [comment]
2.1.7
