### ISSUE TITLE
安装的时候出现错误

### ISSUE THREAD

**Issue by XuShengYuu** [pylixm/django-mdeditor#88]
ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\AOAO\\AppData\\Local\\Temp\\pip-install-9uy2jjmy\\django-mdeditor\\setup.py'"'"'; __file__='"'"'C:\\Users\\AOAO\\AppData\\Local\\Temp\\pip-install-9uy2jjmy\\django-mdeditor\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\AOAO\AppData\Local\Temp\pip-install-9uy2jjmy\django-mdeditor\pip-egg-info'
         cwd: C:\Users\AOAO\AppData\Local\Temp\pip-install-9uy2jjmy\django-mdeditor\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\AOAO\AppData\Local\Temp\pip-install-9uy2jjmy\django-mdeditor\setup.py", line 5, in <module>
        long_description = readme.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 167: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
安装的时候出现以上错误，系统环境win10

**Comment by 312818490** [comment]
https://blog.csdn.net/weixin_39646458/article/details/105080143

**Comment by XuShengYuu** [comment]
> https://blog.csdn.net/weixin_39646458/article/details/105080143
谢谢

**Comment by pylixm** [comment]
同 https://github.com/pylixm/django-mdeditor/issues/72
