### ISSUE TITLE
Release 0.1.17 disappeared from pypi

### ISSUE THREAD

**Issue by robertaistleitner** [pylixm/django-mdeditor#89]
I just got build errors because release 0.1.17 disappeared from pypi:

https://pypi.org/project/django-mdeditor/0.1.17.1/#history

**Comment by pylixm** [comment]
I deleted this version from pypi, you can use the latest version 0.1.18  .

**Comment by robertaistleitner** [comment]
Sorry to hear that as I think it will break build pipelines of people out there (as it was for me).
This one's a good read on why not to delete releases: https://pydist.com/blog/never-delete-a-release

But maybe you have a good reason to do so?

Anyhow - thanks for maintaining this package! 👍

**Comment by pylixm** [comment]
Sorry for this. After I deleted it, I wanted to re-upload version 0.1.17, but pypi does not allow this. At present, it can only maintain the status quo.

**Comment by robertaistleitner** [comment]
No worries, just wanted to know why this happened.
