### ISSUE TITLE
Remove line numbers in Code

### ISSUE THREAD

**Issue by sjay05** [pylixm/django-mdeditor#93]
I would like to remove the line numbers that appear on code like the image below. Is there a quick way I can do this?

![image](https://user-images.githubusercontent.com/41878734/80266924-96a1d680-866c-11ea-8182-7d324138027a.png)

**Comment by jaradc** [comment]
I am a new user as well and am wondering the same.

**Comment by jaradc** [comment]
Kind of got it with some custom css, but not sure this is the best approach:


posts/static/posts/css/posts_custom.css
```
ol.linenums {
    padding-left: 0 !important;
}

ol.linenums li {
    list-style-type: none !important;
}
```

posts/admin.py
```
from django.contrib import admin
from posts.models import Post

@admin.register(Post)
class PostAdmin(admin.ModelAdmin):
    list_display = ('id', 'title', 'user')
    list_display_links = ('title',)

    class Meta:
        model = Post

    class Media:
        css = {'all': ('posts/css/posts_custom.css',)}
        js = ()
```

Still, why doesn't `lineNumbers` work? I came across [several posts](https://stackoverflow.com/questions/51328657/remove-line-numbers-of-plugin-editor-md?rq=1) experiencing the same thing.

**Comment by pylixm** [comment]
The 'lineNumbers' in the configuration is the global edit box line number control, not the code block. The line number of the code block does not support configuration now, it can only be retained. You can also modify the CSS style to achieve it yourself, or have a more elegant solution, please leave a message or submit a PR.
