### ISSUE TITLE
Horizontal Scroll Not Fully Scrolling Right (in Watch and UnWatch mode)

### ISSUE THREAD

**Issue by jaradc** [pylixm/django-mdeditor#96]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/12854767/80841296-f0962500-8bb3-11ea-8690-db9a4731cace.gif)

I am scrolling to the right, but the text is not showing.

Also, is there a way to wrap text?

**Comment by pylixm** [comment]
It is recommended to modify your own text to keep it as short as possible. This should be a problem with mdedtior.js, it has not been updated for a long time. If you are more familiar with javascript, you can fix it yourself. Welcome to submit PR.

**Comment by pylixm** [comment]
There has been no feedback for a long time, and it can be reopened if necessary.
